Repository googleapis/python-datastore, pull requests merged in 2020-11, with the labels that each got.

#111 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#113 docs: adds UPGRADING.md, not to readme, to help inform users about migration to v2
  README.rst
  UPGRADING.md
  docs/UPGRADING.md
  docs/index.rst
Labels: api: datastore, cla: yes

#103 fix: normalize / test deprecation of 'Client.reserve_ids'
  google/cloud/datastore/client.py
  tests/unit/test_client.py
Labels: cla: yes

#115 fix: fix id_or_name property of key class
  google/cloud/datastore/key.py
  tests/unit/test_key.py
Labels: api: datastore, cla: yes

#120 feat: remove six dependency
  google/cloud/datastore/_gapic.py
  google/cloud/datastore/helpers.py
  google/cloud/datastore/key.py
  tests/system/test_system.py
  tests/system/utils/clear_datastore.py
  tests/system/utils/populate_datastore.py
  tests/unit/test__http.py
Labels: api: datastore, cla: yes
