Repository googleapis/python-datastore, pull requests merged in 2020-08, with the labels that each got.

#54 tests: fix unit test broken by google-cloud-core release
  tests/unit/test_client.py
Labels: cla: yes, testing

#36 docs: correct indication of complete key from "partial"
  google/cloud/datastore/client.py
Labels: cla: yes

#58 docs: update docs build (via synth)
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  google/cloud/datastore_v1/proto/datastore_pb2.py
  google/cloud/datastore_v1/proto/entity_pb2.py
  google/cloud/datastore_v1/proto/query_pb2.py
  noxfile.py
  synth.metadata
Labels: cla: yes, context: partial, status: blocked

#57 chore: apply new gapic configuration (from synth)
  google/cloud/datastore_v1/gapic/datastore_client_config.py
  synth.metadata
Labels: automerge, cla: yes, context: partial

#60 feat: pass 'client_options' to base class ctor
  google/cloud/datastore/client.py
  setup.py
Labels: automerge, cla: yes

#63 docs: add docs for admin client
  docs/admin_client.rst
  docs/index.rst
  google/cloud/datastore_admin_v1/gapic/datastore_admin_client.py
  synth.metadata
  synth.py
Labels: cla: yes

#66 fix: smooth over system test bumps
  CONTRIBUTING.rst
  synth.py
  tests/system/utils/populate_datastore.py
Labels: cla: yes

#67 feat: add retry and timeout args to API methods
  google/cloud/datastore/batch.py
  google/cloud/datastore/client.py
  google/cloud/datastore/query.py
  google/cloud/datastore/transaction.py
  tests/unit/test_batch.py
  tests/unit/test_client.py
  tests/unit/test_query.py
  tests/unit/test_transaction.py
Labels: automerge, cla: yes

#71 feat: supply anonymous credentials under emulator
  google/cloud/datastore/client.py
  tests/system/test_system.py
  tests/unit/test_client.py
Labels: cla: yes
