Repository googleapis/python-datastore, pull requests merged in 2020-09, with the labels that each got.

#76 fix: repair implementation of `Client.reserve_ids`
  google/cloud/datastore/client.py
  tests/system/test_system.py
  tests/unit/test_client.py
Labels: api: datastore, cla: yes

#75 docs: add documentation of thread-safe client
  docs/index.rst
Labels: api: datastore, cla: yes

#73 chore: regen with updated protobuf workspace dependency (via synth)
  google/cloud/datastore_admin_v1/proto/datastore_admin_pb2.py
  google/cloud/datastore_admin_v1/proto/index_pb2.py
  google/cloud/datastore_v1/proto/datastore_pb2.py
  google/cloud/datastore_v1/proto/entity_pb2.py
  google/cloud/datastore_v1/proto/query_pb2.py
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#81 chore: enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#88 chore: remove note about editable installs
  CONTRIBUTING.rst
  synth.metadata
Labels: cla: yes, context: full

#87 chore: start tracking obsolete files
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#90 chore: remove note about editable installs
  CONTRIBUTING.rst
  synth.metadata
Labels: cla: yes, context: none

#91 chore: exclude namespace package file from coverage
  .coveragerc
  synth.metadata
Labels: automerge, cla: yes, context: partial, kokoro:force-run

#92 chore: remove note about editable installs
  CONTRIBUTING.rst
  synth.metadata
Labels: cla: yes, context: none
