Repository googleapis/python-datastore, pull requests merged in 2021-08, with the labels that each got.

#205 tests: split systests to separate kokoro job
  .kokoro/presubmit/presubmit.cfg
  .kokoro/presubmit/system-3.8.cfg
  noxfile.py
  owlbot.py
Labels: api: datastore, cla: yes

#207 tests: allow prerelease deps on Python 3.9
  testing/constraints-3.9.txt
Labels: cla: yes, api: datastore

#214 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: cla: yes, api: datastore, automerge, samples

#215 chore: add missing import in owlbot.py
  owlbot.py
Labels: cla: yes, api: datastore

#213 tests: revert testing against prerelease deps on Python 3.9
  testing/constraints-3.9.txt
Labels: cla: yes, api: datastore, automerge

#210 tests: refactor systests to use pytest fixtures / idioms
  google/cloud/datastore/client.py
  google/cloud/datastore/entity.py
  google/cloud/datastore/transaction.py
  tests/system/_helpers.py
  tests/system/conftest.py
  tests/system/test_allocate_reserve_ids.py
  tests/system/test_put.py
  tests/system/test_query.py
  tests/system/test_system.py
  tests/system/test_transaction.py
  tests/system/utils/populate_datastore.py
Labels: cla: yes, api: datastore

#217 chore: migrate to main branch
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  docs/conf.py
  owlbot.py
Labels: cla: yes, api: datastore
