Repository googleapis/python-datastore, pull requests merged in 2022-04, with the labels that each got.

#289 chore: set up CI on v1 branch
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  .gitignore
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/conf.py
  google/cloud/datastore_admin_v1/gapic/datastore_admin_client.py
  google/cloud/datastore_admin_v1/proto/datastore_admin_pb2.py
  google/cloud/datastore_admin_v1/proto/datastore_admin_pb2_grpc.py
  google/cloud/datastore_admin_v1/proto/index_pb2.py
  google/cloud/datastore_v1/gapic/datastore_client.py
  google/cloud/datastore_v1/proto/datastore_pb2.py
  google/cloud/datastore_v1/proto/datastore_pb2_grpc.py
  google/cloud/datastore_v1/proto/entity_pb2.py
  google/cloud/datastore_v1/proto/query_pb2.py
  noxfile.py
  tests/system/test_system.py
  tests/unit/test_client.py
Labels: api: datastore, size: l

#295 chore: allow releases on previous major versions
  .github/release-please.yml
  owlbot.py
Labels: api: datastore, size: s

#283 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v1 release
  setup.py
Labels: api: datastore, size: xs
