Repository googleapis/python-datastore, pull requests merged in 2022-06, with the labels that each got.

#318 fix(deps): require protobuf <4.0.0dev
  setup.py
  testing/constraints-3.6.txt
Labels: api: datastore, size: xs

#322 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: api: datastore, size: s

#323 fix(deps): require protobuf<4.0.0 on v1 branch
  setup.py
Labels: api: datastore, size: xs

#287 feat: support IN/NOT_IN/NOT_EQUAL operators
  google/cloud/datastore/query.py
  tests/unit/test_query.py
Labels: api: datastore, size: s

#312 docs(samples): add samples for IN, NOT_IN, and != operators.
  samples/snippets/noxfile.py
  samples/snippets/noxfile_config.py
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
  samples/snippets/snippets.py
  samples/snippets/snippets_test.py
Labels: api: datastore, samples, size: l
